const fishes = {
  BANGUS: {
    Scientific_Name: "Chanos chanos",
    General_Name: "Milk Fish",
    Type_of_Water_Found_in: "- Marine , FreshWater ,and Brackish ",
    Length_at_first_Maturity: "Range 68 -70 cm ",
    Short_Description:
      "This species is characterized by the following: body elongate and somewhat compressed mouth small and toothless; single dorsal about mid-level of the body; pectoral fins falcate caudal fin large and deeply forked no scutes on belly; branchiostegal rays 4. Colour of the body olive green dorsally; flanks silvery; unpaired fins with dark ",
    Life_cycle_Mating_behavior:
      "Seven stages in the life history of milkfish Chanos chanos are suggested: embryonic, yolksac larval, larval, postlarval, juvenile, sub-adult and adult stages. These were based on morphological differences and on their particular ecological requirements.Mating behavior -Spawning and fertilization take place at night.",
    Location_on_Map: "Bangus.jpg",
    endangered: true,
  },
  BARRAMUNDI: {
    Scientific_Name: "Lates calcarifer",
    General_Name: "Asian sea bass",
    Type_of_Water_Found_in: "- Marine , FreshWater ,and Brackish ",
    Length_at_first_Maturity: "Range 29 - 60 cm",
    Short_Description:
      "Dorsal spines (total): 7 - 9; Dorsal soft rays (total): 10-11; Anal spines: 3; Anal soft rays: 7 - 8. Body elongate; mouth large, slightly oblique, upper jaw extending behind the eye. Lower edge of preopercle serrated, with strong spine at its angle; opercle with a small spine and with a serrated flap above the origin of the lateral line. Caudal fin rounded. ",
    Life_cycle_Mating_behavior:
      "Breed in estuaries throughout the Indo-Pacific. Maturing male barramundi migrate downstream from freshwater habitats at the start of the wet (monsoon) season to spawn with resident females in estuaries  and on tidal flats outside the mouths of rivers . Barramundi spawn on the full moon and new moon, primarily at the beginning of an incoming tide which carries the eggs into the estuary Barramundi are broadcast spawners that aggregate to spawn .",
    Location_on_Map: "Barramundi.jpg",
    endangered: false,
  },
  INDIAN_ANCHOVY: {
    Scientific_Name: "Stolephorus indicus",
    General_Name: "Hardenberg's anchovy",
    Type_of_Water_Found_in: "Marine brackish pelagic-neritic ",
    Length_at_first_Maturity: "Range 12-15 cm",
    Short_Description:
      "Dorsal spines (total): 0; Dorsal soft rays (total): 15-17; Anal spines: 0; Anal soft rays: 19 - 21. Diagnosis: Body slender, elongate, rather round in cross-section, belly rounded, with 2-6 small needle-like pre-pelvic scutes; maxilla tip pointed, reaching to or only just beyond front border of pre-operculum;  ",
    Life_cycle_Mating_behavior:
      "In Manila Bay, migrates out into deeper and more saline water to breed (at about 9 cm SL and above), returning immediately thereafter.",
    Location_on_Map: "Indian_anchovy.jpg",
    endangered: false,
  },
  INDIAN_MACKREL: {
    Scientific_Name: "Rastrelliger kanagurta",
    General_Name: "Mackerel",
    Type_of_Water_Found_in: "Marine pelagic-neritic oceanodromous  ",
    Length_at_first_Maturity: "range 20 - 24.5 cm ",
    Short_Description:
      "Dorsal spines (total): 8 - 11; Dorsal soft rays (total): 12; Anal spines: 0; Anal soft rays: 12. Head longer than body depth. Maxilla partly concealed, covered by lachrymal bone but extending to about hind margin of eye. Bristles on longest gill raker 105 on one side in specimens of 12.7 cm, 140 in 16 cm, and 160 in 19 cm fork length specimens. A black spot on body near lower margin of pectoral fin. Interpelvic process small and single. Swim bladder present. Anal spine rudimentary",
    Life_cycle_Mating_behavior:
      "Currently the Indian Mackerel fish is widespread in the Indo-West Pacific from South Africa, Seychelles and Red Sea east through Indonesia and off northern Australia to Melanesia, Micronesia, Samoa, China and the Ryukyu Islands",
    Location_on_Map: "Indian_Mackrel.jpg",
    endangered: false,
  },
  TARALI: {
    Scientific_Name: "Sardinella longiceps",
    General_Name: "Indian oil sardine , Malabar sardine",
    Type_of_Water_Found_in: "Marine",
    Length_at_first_Maturity: "Range 15-30 cm",
    Short_Description:
      " Coastal pelagic . Forms schools in coastal waters and strongly migratory. Feeds mainly on phytoplankton (especially diatoms) and small crustaceans . Breeds once a year off western coasts of India when temperatures and salinity are low during the southwest monsoon months. Spawning peaks in August-September. Occurs at temperatures of 22.0-28.0 °C (Ref. 3689). Marketed fresh, dried and dried-salted. Also sold smoked and canned . Also made into fish meal and fish balls.",
    Life_cycle_Mating_behavior: "Spawning usually takes place at night",
    Location_on_Map: "Tarali.jpg",
    endangered: false,
  },
  INDIAN_SALMON: {
    Scientific_Name: "Eleutheronema tetradactylum",
    General_Name: "Indian Salmanadar",
    Type_of_Water_Found_in: "Marine",
    Length_at_first_Maturity: "Range 14-17 cm",
    Short_Description:
      " This species is distinguished with the following characters: second dorsal fin soft rays 14 (rarely 13 or 15) pectoral fin rays 16-18 (mode 17, rarely 15 or 19), pectoral filaments 4; pored lateral line scales 71-80 (mode 73); scale rows above lateral line 9-12, below 13-15 (14); vomer with deciduous tooth plates on both sides, except in juveniles (< ca. 7.0 cm SL); posterior part of maxilla deep, 3-4% of SL; short tooth plate extension onto lateral surface of lower jaw, 7-9% SL. Colour of upper sides of head and trunk with slight darkish silver tinge, becoming lighter in lower sides; anterior margins of first and second dorsal fins blackish, remaining parts translucent and slightly blackish, respectively; pectoral fin membranes vivid yellow in life, except in large specimens > ca 35 cm SL which is dusky yellow; pectoral filaments white; anterior margin of pelvic fin yellow and other parts white; base of caudal",
    Life_cycle_Mating_behavior: "Spawning usually takes place at night",
    Location_on_Map: "Indian_Salmon.jpg",
    endangered: false,
  },
  KATLA: {
    Scientific_Name: "Catla catla",
    General_Name: "Catla fish ",
    Type_of_Water_Found_in: "Freshwater ",
    Length_at_first_Maturity: "Range 2.5-5cm",
    Short_Description:
      " Dorsal soft rays (total): 17; Anal spines: 0; Anal soft rays: 7 - 8. Body deep, with depth 2.5 to 3 times in standard length . Has a large, upturned mouth , with a prominent protruding lower jaw . Pectoral fins long, extending to pelvic fins; scales conspicuously large .Threat to human : Harmless ; highly commercial; aquaculture: commercial; gamefish ",
    Life_cycle_Mating_behavior:
      "Adults occur in rivers, lakes and culture ponds (Ref. 41236). Mature individuals breed in rivers",
    Location_on_Map: "katla.jpg",
    endangered: false,
  },
  ROHU: {
    Scientific_Name: "Roho labeo",
    General_Name: "Rau, Rohiti",
    Type_of_Water_Found_in: "Freshwater ",
    Length_at_first_Maturity: "range 35-45 cm",
    Short_Description:
      "Dorsal fin with 12-14 1/2 branched rays; lower profile of head conspicuously arched; short dorsal fin with anterior branched rays shorter than head; 12-16 predorsal scales ; snout without lateral lobe  ",
    Life_cycle_Mating_behavior:
      "Spawns in middle reaches of rivers, where flood water spreads in more or less limpid shallows over fertile flats, well above tidal reaches; also in reservoirs and bundh-type tanks.",
    Location_on_Map: "Rohu.jpg",
    endangered: false,
  },
  TUNA: {
    Scientific_Name: " Thunnini",
    General_Name: " Albacore",
    Type_of_Water_Found_in: " Marine",
    Length_at_first_Maturity: "range 20-25 cm",
    Short_Description:
      "Dorsal fin with 12-14 1/2 branched rays; lower profile of head conspicuously arched; short dorsal fin with anterior branched rays shorter than head; 12-16 predorsal scales ; snout without lateral lobe  ",
    Life_cycle_Mating_behavior:
      "Spawns in middle reaches of rivers, where flood water spreads in more or less limpid shallows over fertile flats, well above tidal reaches; also in reservoirs and bundh-type tanks.",
    Location_on_Map: "tuna.jpg",
    endangered: false,
  },
  POMFRET: {
    Scientific_Name: " Bramidae",
    General_Name: "white pomfret",
    Type_of_Water_Found_in: " Marine",
    Length_at_first_Maturity: "27-28 cm",
    Short_Description:
      "Dorsal fin with 12-14 1/2 branched rays; lower profile of head conspicuously arched; short dorsal fin with anterior branched rays shorter than head; 12-16 predorsal scales ; snout without lateral lobe  ",
    Life_cycle_Mating_behavior:
      "Spawns in middle reaches of rivers, where flood water spreads in more or less limpid shallows over fertile flats, well above tidal reaches; also in reservoirs and bundh-type tanks.",
    Location_on_Map: "pomfret.jpg",
    endangered: false,
  },
  MAHSEER_TOR_TOR: {
    Scientific_Name: " Bramidae",
    General_Name: "Maheer",
    Type_of_Water_Found_in: " Marine,freshWater",
    Length_at_first_Maturity: "25-35 cm",
    Short_Description:
      "Dorsal fin with 12-14 1/2 branched rays; lower profile of head conspicuously arched; short dorsal fin with anterior branched rays shorter than head; 12-16 predorsal scales ; snout without lateral lobe  ",
    Life_cycle_Mating_behavior:
      "Spawns in middle reaches of rivers, where flood water spreads in more or less limpid shallows over fertile flats, well above tidal reaches; also in reservoirs and bundh-type tanks.",
    Location_on_Map: "mahseer.jpg",
    endangered: false,
  },
  MANGROVE_RED_SNAPPER: {
    Scientific_Name: " Bramidae",
    General_Name: "Mangrove red snapper",
    Type_of_Water_Found_in: " Marine,freshwater",
    Length_at_first_Maturity: "22-28 cm",
    Short_Description:
      "Dorsal fin with 12-14 1/2 branched rays; lower profile of head conspicuously arched; short dorsal fin with anterior branched rays shorter than head; 12-16 predorsal scales ; snout without lateral lobe  ",
    Life_cycle_Mating_behavior:
      "Spawns in middle reaches of rivers, where flood water spreads in more or less limpid shallows over fertile flats, well above tidal reaches; also in reservoirs and bundh-type tanks.",
    Location_on_Map: "mangroove.jpg",
    endangered: false,
  },
};

const fishNutrition = {
  BANGUS: {
    Calories: 126,
    Total_fat: "7%",
    Cholesterol: "15%",
    Sodium: "3%",
    Calcium: "3%",
    Vitamin_D: "n/a",
    Iron: "2%",
    Potassium: "5%",
  },
  BARRAMUNDI: {
    Calories: 108,
    Total_fat: "8%",
    Cholesterol: "20%",
    Sodium: "n/a",
    Calcium: "3%",
    Vitamin_D: "n/a",
    Iron: "2%",
    Potassium: "5%",
  },
  INDIAN_ANCHOVY: {
    Calories: 133,
    Total_fat: "15%",
    Cholesterol: "12%",
    Sodium: "5%",
    Calcium: "1%",
    Vitamin_D: "n/a",
    Iron: "2%",
    Potassium: "5%",
  },
  INDIAN_MACKREL: {
    Calories: 117,
    Total_fat: "10%",
    Cholesterol: "12%",
    Sodium: "5%",
    Calcium: "4%",
    Vitamin_D: "2",
    Iron: "6%",
    Potassium: "5%",
  },
  TARALI: {
    Calories: 115,
    Total_fat: "7%",
    Cholesterol: "15%",
    Sodium: "3%",
    Calcium: "3%",
    Vitamin_D: "n/a",
    Iron: "2%",
    Potassium: "5%",
  },
  INDIAN_SALMON: {
    Calories: 109,
    Total_fat: "7%",
    Cholesterol: "15%",
    Sodium: "3%",
    Calcium: "3%",
    Vitamin_D: "n/a",
    Iron: "2%",
    Potassium: "5%",
  },
  ROHU: {
    Calories: 121,
    Total_fat: "8%",
    Cholesterol: "15%",
    Sodium: "3%",
    Calcium: "5%",
    Vitamin_D: "4%",
    Iron: "2.8%",
    Potassium: "5%",
  },
  KATLA: {
    Calories: 119,
    Total_fat: "12%",
    Cholesterol: "14%",
    Sodium: "3%",
    Calcium: "3%",
    Vitamin_D: "1%",
    Iron: "2%",
    Potassium: "3%",
  },
  TUNA: {
    Calories: 118,
    Total_fat: "11%",
    Cholesterol: "15%",
    Sodium: "3%",
    Calcium: "3%",
    Vitamin_D: "n/a",
    Iron: "2%",
    Potassium: "5%",
  },
  POMFRET: {
    Calories: 141,
    Total_fat: "16%",
    Cholesterol: "14%",
    Sodium: "3%",
    Calcium: "3%",
    Vitamin_D: "4%",
    Iron: "2%",
    Potassium: "5%",
  },
  MAHSEER_TOR_TOR: {
    Calories: 122,
    Total_fat: "13%",
    Cholesterol: "16%",
    Sodium: "3%",
    Calcium: "4%",
    Vitamin_D: "n/a",
    Iron: "2%",
    Potassium: "5%",
  },
  MANGROVE_RED_SNAPPER: {
    Calories: 133,
    Total_fat: "14%",
    Cholesterol: "13%",
    Sodium: "3%",
    Calcium: "3%",
    Vitamin_D: "2%",
    Iron: "3%",
    Potassium: "5%",
  },
};
export { fishes, fishNutrition };
